on: [ push ]
name: build
jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        with:
          command: test
  build:
    name: Run build
    needs: [ lint, test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: build
        uses: actions-rs/cargo@v1
        with:
          command: build